public class primitiveTypes {
    /* PRIMITIVE TYPES - 
    
    #1- BYTE(8 BIT)- -127 TO 128
    #2- SHORT(16 BIT)- -32,768 TO 32,767
    #3- INT(32 BIT)- -2^31 TO 2^31-1
    #4- LONG(64 BIT)- 0 TO 2^64-1 . USED FOR VERY LARGE NUMBERS THAT 'INT' CANNOT HANDLE
    #5- FLOAT(32 BIT IEEE 754 FLOATING POINT)- NEVER USE FOR PRECISION VALUES SUCH AS CURRENCY
    #6- DOUBLE(64 BIT IEEE 754 FLOATING POINT) - USE FOR DECIMAL VALUES 
    #7- BOOLEAN - TRUE OR FALSE;
    #8- CHAR(16 BIT SINGLE UNICODE CHARACTER)- A;
    
    */ 

public static void main(String[] args) {
    
}
    
}
